- id: '1562721049899'
  alias: Send Message - Garage
  hide_entity: true
  initial_state: true
  trigger:
  - entity_id: cover.garage_door
    for: 00:00:10
    platform: state
    to: open
  condition: []
  action:
    service: notify.ios_oreo
    data:
      title: "Garage Door Notification"
      message: The garage door is open
      data:
        push:
          badge: 0
          category: garage1
        action_data:
          entity_id: cover.garage_door
- id: '1562731678153'
  alias: IOS app notification action garage1
  hide_entity: true
  initial_state: true
  trigger:
  - event_data:
      actionName: CLOSE_DOOR
    event_type: ios.notification_action_fired
    platform: event
  condition: []
  action:
  - service: cover.close_cover
